# Generated by Django 3.1.3 on 2020-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=50)),
                ('map_url', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('test_blood', models.BooleanField()),
                ('donate_blood', models.BooleanField()),
            ],
        ),
    ]
