# Generated by Django 3.1.3 on 2020-12-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0003_auto_20201208_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='about',
        ),
    ]
