# Generated by Django 3.1.3 on 2020-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0004_remove_hospital_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='x',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hospital',
            name='y',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
        ),
    ]
