# Generated by Django 3.1.3 on 2020-12-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0005_auto_20201209_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='direction_url',
        ),
    ]
