# Generated by Django 3.1.3 on 2020-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0006_remove_hospital_direction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(default='LOREM IPSUM', max_length=500),
        ),
    ]
